{% set name = "metocean-ml" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:  
  url: https://pypi.io/packages/source/m/metocean-ml/metocean_ml-{{ version }}.tar.gz
  sha256: d2d2b72ac745932cf315c9333d1a774edc0daf8caf8be3fd6049d2327899b7f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.7.0
    - numpy >=1.17.0
    - matplotlib-base >=3.1.0
    - pandas
    - pip
    - scipy
    - xarray
    - scikit-learn
    - keras
    - tensorflow

test:
  imports:
    - metocean_ml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MET-OM/metocean-ml
  summary: 'Package for machine learning  for metocean data'
  license: GPL-3.0
  license_file: LICENSE
  dev_url: https://github.com/MET-OM/metocean-ml

extra:
  recipe-maintainers:
    - KonstantinChri
